### ISSUE TITLE
"Open AppMaps" quickstart view doesn't refresh

### ISSUE THREAD

**Issue by dividedmind** [applandinc/appmap-intellij-plugin#103]
After running tests and recording some appmaps, the AppMaps side pane is populated, but the "Open AppMaps" quickstart view still doesn't show any maps. It seems like indexing didn't run correctly on the changes. I was able to get the view to show appmaps by running `/home/user/.cache/JetBrains/appland-plugin/appmap/3.34.0/appmap-linux-x64 index` manually.

I couldn't reproduce it after removing the appmaps manually. This could be related to the fact that I started in a totally fresh project without appmap installed.

**Comment by jansorg** [comment]
Which project did you use to test this?
I've found issues with spring-petclinic, but this may be related to the Maven agent (?).
Watching the filesystem for changes to appmap files is supposed to work...

**Comment by dividedmind** [comment]
Missed your comment and I don't think it matters anymore, but FWIW it was https://github.com/land-of-apps/sample_app_6th_ed/

**Comment by jansorg** [comment]
Should be working with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
