### ISSUE TITLE
Install AppMap Agent Link doesn't Navigate to Install page

### ISSUE THREAD

**Issue by petecheslock** [applandinc/appmap-intellij-plugin#106]
IntelliJ IDEA 2022.1.4 (Community Edition)
Build #IC-221.6008.13, built on July 19, 2022
Runtime version: 11.0.15+10-b2043.56 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Non-Bundled Plugins:
    appland.appmap (0.8.0-6)

Kotlin: 221-1.6.21-release-337-IJ6008.13

0.8.0-6 of the plugin

To recreate - clone the [sample_app_6th_ed](https://github.com/land-of-apps/sample_app_6th_ed)
Checkout the codespaces-devcontainer branch.

https://www.loom.com/share/ce243402b0f045b69a09ed194aa60c96

<img width="398" alt="Screen Shot 2022-09-09 at 9 21 37 AM" src="https://user-images.githubusercontent.com/511733/189359582-9aa49a77-e59f-46a0-a181-f3f63613ad62.png">

The link in the "no appmaps found" does not go anywhere but the link at the bottom of the screenshot does.

**Comment by jansorg** [comment]
Thanks! I managed to push debugging code :( 
Fixed by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/7eb6a7dc637392268fbaa415e19ca1f83f8f9656

**Comment by jansorg** [comment]
Fixed with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
