### ISSUE TITLE
Explore AppMaps Page does not populate "selected code objects". Code Objects are not indexed

### ISSUE THREAD

**Issue by petecheslock** [applandinc/appmap-intellij-plugin#108]
IntelliJ IDEA 2022.1.4 (Community Edition)
Build #IC-221.6008.13, built on July 19, 2022
Runtime version: 11.0.15+10-b2043.56 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Non-Bundled Plugins:
appland.appmap (0.8.0-6)

Kotlin: 221-1.6.21-release-337-IJ6008.13

0.8.0-6 of the plugin

To recreate - clone the [sample_app_6th_ed](https://github.com/land-of-apps/sample_app_6th_ed)
Checkout the codespaces-devcontainer branch.

Install AppMap, Run the tests `APPMAP=true bundle exec rails test` - then AppMaps will populate on the right side column.  Continuing the onboarding flow - the "Explore AppMaps" page has missing Selected code objects. 
<img width="1224" alt="Screen Shot 2022-09-09 at 11 08 45 AM" src="https://user-images.githubusercontent.com/511733/189382821-ba5efb32-40da-4ce1-bcfd-9675b13a0d75.png">

In VS Code you'll see the following as well - missing code objects.  
<img width="1397" alt="Screen Shot 2022-09-09 at 11 08 28 AM" src="https://user-images.githubusercontent.com/511733/189382956-33526b5a-ac71-4fe2-8373-083283536c2c.png">

If I run the index command via npx
`npx @appland/appmap index`
Then the code objects will populate.  
<img width="757" alt="Screen Shot 2022-09-09 at 11 11 27 AM" src="https://user-images.githubusercontent.com/511733/189383380-a2d97d6a-9008-4ff4-adb3-c371b3e028a8.png">

**Comment by jansorg** [comment]
I believe that this is fixed now by @dustinbyrne's PR https://github.com/applandinc/appmap-intellij-plugin/pull/105

**Comment by jansorg** [comment]
Fixed with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
