### ISSUE TITLE
Explore AppMaps page displays more than 5 SQL queries to explore

### ISSUE THREAD

**Issue by petecheslock** [applandinc/appmap-intellij-plugin#109]
IntelliJ IDEA 2022.1.4 (Community Edition)
Build #IC-221.6008.13, built on July 19, 2022
Runtime version: 11.0.15+10-b2043.56 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Non-Bundled Plugins:
appland.appmap (0.8.0-6)

Kotlin: 221-1.6.21-release-337-IJ6008.13

0.8.0-6 of the plugin

To recreate - clone the [sample_app_6th_ed](https://github.com/land-of-apps/sample_app_6th_ed)
Checkout the codespaces-devcontainer branch.

Related to https://github.com/applandinc/appmap-intellij-plugin/issues/108
After i manually index the appmaps and generate the selected code objects the explore appmaps page shows more than the top 5 sql queries.  

VS Code:  
<img width="922" alt="Screen Shot 2022-09-09 at 11 16 31 AM" src="https://user-images.githubusercontent.com/511733/189384389-d3e72f53-8b77-428a-b679-09650cf12716.png">

Intellij: https://www.loom.com/share/cf06a4dd66ac4df69bd562f50036d74d

**Comment by jansorg** [comment]
Should be fixed with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
