### ISSUE TITLE
AppMaps are not indexed

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#111]
AppMaps are not indexed. The Selected Code Objects panel is empty:

![Image](https://user-images.githubusercontent.com/45714532/189401059-88dbf9aa-0b1a-4b8e-b893-871dbc0d2165.png)

To recreate:

1. `git clone https://github.com/land-of-apps/juice-shop.git`
2.  Switch to `fix-install-errors` branch
5.  `npm install`
6. Install AppMap plugin / extension
7. Copy `npx` install command and use defaults
8. Run `npx appmap-agent-js -- mocha -r ts-node/register test/server/**/*.ts` to generate AppMaps

**Comment by jansorg** [comment]
Could you test this again with the latest 0.8.1-7 preview at https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview? I believe it's fixed now

**Comment by jansorg** [comment]
Should be working with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
