### ISSUE TITLE
Quickstart link icons do not update when the step has been completed

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-intellij-plugin#113]
Upon completing a step in the install guide, the quickstart step should depict its completion state.

IntelliJ
![Image](https://user-images.githubusercontent.com/8737782/189413852-c14af65a-a4a5-40d1-a832-083e8faf3004.png)

VS Code
![Image](https://user-images.githubusercontent.com/8737782/189413915-c72994a6-2b9d-4c69-8ae5-bc7cd36ca47b.png)

**Comment by jansorg** [comment]
Should be fixed with 0.11.0-2, please reopen if it's still a bug on your machine. This isn't implementing the "lock" icon as in VSCode.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
