### ISSUE TITLE
Long SQL queries should be truncated in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#121]
Currently, long SQL queries are displayed in their entirety in the `Explore AppMaps` instruction page:

![Image](https://user-images.githubusercontent.com/45714532/190472753-34c384c9-8c18-444d-8211-b87cf8adeae4.png)

**Comment by jansorg** [comment]
Weird, I though I made that change. Perhaps I forgot to push :(

**Comment by jansorg** [comment]
Fixed by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/ac8c7f48b273c63c19ef71daef8ff11f19cd0dce for the next preview

**Comment by jansorg** [comment]
Fixed with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
