### ISSUE TITLE
AppMap Runtime Analysis should show the number of findings in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#122]
Findings are being generated, but the `AppMap Runtime Analysis` instructions page still says that `This project has not been scanned yet`:

![Image](https://user-images.githubusercontent.com/45714532/190473700-c2c947bc-1f61-4a68-8c16-31104a4e0352.png)

For reference, here is how it looks in VS Code:

![Image](https://user-images.githubusercontent.com/45714532/190473877-0c682932-d61d-4327-9c31-fd2eb48eb78c.png)

**Comment by jansorg** [comment]
Fixed with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
