### ISSUE TITLE
Findings should have squiggles in the source code in the JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#123]
Here's how it looks in VS Code:

![Image](https://user-images.githubusercontent.com/45714532/190475767-3c2a60a1-4385-4dae-b7dc-55f15176b0f5.png)

Here's how it looks in RubyMine:

![Image](https://user-images.githubusercontent.com/45714532/190475919-09810782-2379-4789-9159-1f3003754102.png)

**Comment by jansorg** [comment]
Should be fixed by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/c593fa50e218d28b619e9645f106b8f2e217eb77 for the next preview. Lines were 1-based in the stacktrace, but the SDK expects 0-based line numbers.
