### ISSUE TITLE
Scanner doesn't run in Windows in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#124]
Tested with RubyMine on Windows with Rails sample app.

The scanner is present in the folder `C:\Users\ahtro\AppData\JetBrains\appland-plugin\scanner\` but findings are not generated. If I manually execute the scanner with `scan --all` then findings are generated.

**Comment by jansorg** [comment]
Is this a duplicate of https://github.com/applandinc/appmap-js/issues/726?

**Comment by ahtrotta** [comment]
Yeah, looks like it is. Sorry, I didn't see that when I made this.

**Comment by jansorg** [comment]
Duplicate of https://github.com/applandinc/appmap-js/issues/726
