### ISSUE TITLE
Interesting UI bug: scrolling in AppMap makes IntelliJ scroll editor window tabs.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-intellij-plugin#22]
This is not a blocker for the initial release. To replicate, open multiple editors and then scroll with a mouse / trackpad in an AppMap.

https://www.loom.com/share/aa2d0d2f35054c3a807a13824b1991d0

**Comment by jansorg** [comment]
Hopefully fixed by this https://youtrack.jetbrains.com/issue/IDEA-241513 in 2021.1.1.

There's also https://youtrack.jetbrains.com/issue/IDEA-267939, but hopefully it's not affecting the AppMap plugin.

**Comment by ptrdvrk** [comment]
I can no longer replicate this problem with the latest build / js library. Closing now, will re-open if it surfaces again.
