### ISSUE TITLE
AppMaps can be uploaded from the IntelliJ plugin

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-intellij-plugin#31]
See the VSCode implementation as a reference for this ticket: https://github.com/applandinc/vscode-appland/blob/feat/appmap-upload/src/appmapUploader.ts 
- a new "Upload" icon exists in the AppMap diagram
- when user clicks on the icon, a "Upload? Y/N" confirmation message is displayed. When confirmed by the user, the upload proceeds
- The upload action opens a new web browser window and posts the AppMap to the upload endpoint on https://app.land

**Comment by ptrdvrk** [comment]
Upload icon: 
[appmap_upload_icon.svg.txt](https://github.com/applandinc/appmap-intellij-plugin/files/6742033/appmap_upload_icon.svg.txt)

**Comment by jansorg** [comment]
This has been merged already.
