### ISSUE TITLE
Remote recording controls exist in the plugin

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-intellij-plugin#33]
- action that opens start recording dialog
- UI button that opens start recording dialog
- action that stops recording and saves recording to a file in project folders

Loom of (incomplete) VSCode implementation: https://www.loom.com/share/7db2f60b7d814336a0764beef027370f
 - needs better UI for entering URL and file name/directory

Sample instrumented server for testing: https://discourse.appland.dev/

Acceptance criteria
 - When no remote recording is in progress, user can start remote recording from the UI or with a "AppMap: Start remote recording" action
     - user can enter a new URL of the recorded app, or pick a previously entered URL for the current project
 - UI indicates that the remote recording is currently in progress
 - When remote recording is in progress, user can stop the remote recording from the UI or with a "AppMap: Stop remote recording" action
    - user can pick a destination folder for the saved appmap, and the appmap name
    - the destination folder is remembered from the previously recorded appmap for the current project
  - when the recording cannot be started, stopped or the AppMap saved successfully, a user friendly error message is displayed together with a link to a troubleshooting documentation (link tbd)

**Comment by jansorg** [comment]
@ptrdvrk Is "the appmap name" the name of the file on disk or the name in the metadata?
If it's the name in the metadata, am I supposed to override this in the JSON returned by the API or pass it to the `DELETE` call? The API doesn't have a parameter for this, though.

**Comment by jansorg** [comment]
@ptrdvrk 

1. Do you provide icons for the start and stop actions or should I pick some from the existing set? 

2. I'm uncertain about the best way to handle the start and stop. 
How is "When no remote recording is in progress" supposed to work?
- Should the last entere URL be checked? Or should all the last URLs be checked?
- What should happen after a restart of the IDE when a recording was active?

**Comment by ptrdvrk** [comment]
Hi Joachim

- the recording icons are here: https://github.com/applandinc/vscode-appland/tree/feature/remote-recording/images
- the entered AppMap name is used both as a basis for the file name and in the appmap metadata. This is the implementation in VSCode: https://github.com/applandinc/vscode-appland/blob/754d0a7679cb53ac2ac418688b3591f31411e199/src/remoteRecording.ts#L83-L100
- the start logic in VSCode is here: https://github.com/applandinc/vscode-appland/blob/754d0a7679cb53ac2ac418688b3591f31411e199/src/remoteRecording.ts#L50-L75
  - Let me review with Dustin tomorrow whether we should be checking the recording status prior to starting recording to catch situations where the recording was started in other than the current IDE session

**Comment by ptrdvrk** [comment]
@jansorg FYI, I am discussing this with Dustin: https://github.com/applandinc/vscode-appland/issues/201

**Comment by jansorg** [comment]
@ptrdvrk How should the UI show that a recording is in progress? Here are a few alternatives:
1. With a notification balloon. A user can close or disable these notifications.
2. With a new icon in the status bar. The user can configure the bar to hide the icon.
3. With a progress task, displayed similar to "Updating indices..." ([screenshot](https://jetbrains.github.io/ui/controls/progress_bar/#in-status-bar)). The user can't hide it, but click it to cancel it.
