### ISSUE TITLE
Users can open the most recently modified AppMap file in the project with a "AppMap: Open the most recently modified AppMap" action in the IDE.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-intellij-plugin#4]

**Comment by jansorg** [comment]
@ptrdvrk Is that the most recent, but closed file? Or should it switch to the most recently opened file if it's still opened in a tab?

**Comment by ptrdvrk** [comment]
It should open the most recently updated file, based on its timestamp. If already opened in a tab, let's focus on this tab.

**Comment by jansorg** [comment]
(Sorry, I misread the title as "most recently opened")
Okay. I'll have to check if there's an efficient way lookup that file, though.
