### ISSUE TITLE
IntelliJ plugin is published in JetBrains repo and can be installed from the Marketplace.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-intellij-plugin#5]
@ptrdvrk This is what's needed:
- [x] A plugin logo SVG, which follows the guidelines at https://plugins.jetbrains.com/docs/intellij/plugin-icon-file.html#plugin-logo-requirements
- [x] Updated description in plugin.xml, [link](https://github.com/applandinc/appmap-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml#L6)
- [x] Verify that the ID in plugin.xml is what you want, it can't be changed once the plugin is on the Marketplace, [link](https://github.com/applandinc/appmap-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml#L2)
- [x] Verify the plugin's name. The name is the user-visible title used on the Marketplace and in the IDEs, [link](https://github.com/applandinc/appmap-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml#L3)
- [x] Register an user account on the marketplace, https://plugins.jetbrains.com/
- [x] Login and create a new organization, https://plugins.jetbrains.com/author/me/organizations
- [x] Update the `<vendor>` in plugin.xml to reference the new organization, [link](https://github.com/applandinc/appmap-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml#L5)
- [x] MIT License specified for the repo

**Comment by ptrdvrk** [comment]
Thank you Joachim. I'll take a stab at those today. How is the publishing process executed, is that via some gradle plugin/task?

**Comment by ptrdvrk** [comment]
The plugin logo is at /src/main/resources/icons/appland_logo.svg

**Comment by ptrdvrk** [comment]
@jansorg please review the submitted information.

**Comment by jansorg** [comment]
Done, the updated information seems fine to me. I copied the logo to the location where the IDEs expect the plugin logo.

**Comment by ptrdvrk** [comment]
@jansorg the repo now has the MIT License.

**Comment by ptrdvrk** [comment]
Uploaded / submitted for review.
