### ISSUE TITLE
Plugin/marketplace documentation page exists.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-intellij-plugin#6]

**Comment by jansorg** [comment]
@ptrdvrk Which documentation is this? 

On the marketplace, there's the plugin's page, e.g. https://plugins.jetbrains.com/plugin/13841-bashsupport-pro
You can upload screenshots after the first version has been uploaded.  

The text below the screenshots is the content of the `<description>` inside the plugin.xml file. 
The first sentence (up to ~140 characters) is displayed as the short summary in lists, e.g. in the IDEs or in "Updated plugins" on the marketplace's front page.

The content of `What's new` is read from tag `<change-notes>` of plugin.xml.

**Comment by ptrdvrk** [comment]
I'll provide the change notes and the updated description later today, thank you for the clarification @jansorg !
