### ISSUE TITLE
Support JetBrains 2022.1 IDEs

### ISSUE THREAD

**Issue by jansorg** [applandinc/appmap-intellij-plugin#72]
The first EAP (i.e. preview) releases of the 2022.1 JetBrains IDEs were published, https://blog.jetbrains.com/idea/2022/01/intellij-idea-2022-1-eap-1/ Most likely, the final release will be published in April 2022.

@apotterri 
The AppLand plugin needs adjustment to be compatible with the new version. Please let me know if I should work on this.

**Comment by apotterri** [comment]
What's the nature of the changes that need to be made? Can you give a sense of how much effort it will require?

**Comment by jansorg** [comment]
At least compatibility needs to be declared with 2022.1 and tests need to be updated to run with 2022.1. Needed effort is most likely in the range of ~1 hour. If it turns out that compatibility needs more work, it would be clear after that hour.

**Comment by apotterri** [comment]
Ok. Yes, please go ahead and declare compatibility and update the tests.
