### ISSUE TITLE
AppMap incorrectly identifies Rails project as Javascript

### ISSUE THREAD

**Issue by petecheslock** [applandinc/appmap-intellij-plugin#83]
AppMap plugin pre-release version 0.8.0
IntelliJ IDEA 2022.1.2 (Community Edition)

To recreate - clone the [sample_app_6th_ed](https://github.com/land-of-apps/sample_app_6th_ed)
Checkout the `codespaces-devcontainer` branch.  

Click on "install appmap agent"

The install wizard incorectly identifies as a Javascript project
<img width="673" alt="Screen Shot 2022-08-19 at 1 13 58 PM" src="https://user-images.githubusercontent.com/511733/185672247-cb0a0635-52f1-43c5-9a21-d9fbd1ac6cfd.png">

[Loom recording](https://www.loom.com/share/af59f71a9f6d42fd8a9ef82ffea25b35)

**Comment by jansorg** [comment]
I wasn't able to reproduce this on Linux with a fresh clone of the project and branch.
Do you have any file changes in the project?

![Screenshot_20220822_170706](https://user-images.githubusercontent.com/11473063/185954930-d1562b89-2a65-4183-8460-5f6c5e40a8ee.png)

**Comment by brikelly** [comment]
Could potentially be caused by the IntelliJ detection code not yet treating gitignore specs correctly

**Comment by jansorg** [comment]
This was indeed caused by the missing support for .gitignore. https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/cde240cc330a7c397c67894fbe601ab67cb8f57c fixes this

**Comment by petecheslock** [comment]
Confirmed fixed in `0.8.0-3`
