### ISSUE TITLE
Copy Command helper buttons in AppMap installer wizard do not copy data into clipboard

### ISSUE THREAD

**Issue by petecheslock** [applandinc/appmap-intellij-plugin#84]
AppMap plugin pre-release version 0.8.0
IntelliJ IDEA 2022.1.2 (Community Edition)

To recreate - clone the [sample_app_6th_ed](https://github.com/land-of-apps/sample_app_6th_ed)
Checkout the `codespaces-devcontainer` branch.

In the "Using Appmap tab" on the first and other windows of the install wizard, the copy buttons don't actually pull the data into the users' clipboard.  
<img width="641" alt="Screen Shot 2022-08-19 at 1 16 47 PM" src="https://user-images.githubusercontent.com/511733/185673049-38f14984-bae0-4a41-b544-e90732bde0b7.png">

[Loom video recording](https://www.loom.com/share/267372b942334aa6948630c9a18506d5)

**Comment by jansorg** [comment]
Fixed by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/d651c1217f523edb3c96fb44bfca29580b61b91e

**Comment by petecheslock** [comment]
Confirmed fixed on `0.8.0-3`
