### ISSUE TITLE
Open AppMap stage of the install wizard doesn't refresh when AppMaps have been created

### ISSUE THREAD

**Issue by petecheslock** [applandinc/appmap-intellij-plugin#85]
AppMap plugin pre-release version 0.8.0
IntelliJ IDEA 2022.1.2 (Community Edition)

To recreate - clone the [sample_app_6th_ed](https://github.com/land-of-apps/sample_app_6th_ed)
Checkout the `codespaces-devcontainer` branch.

When following the installation wizard and running the record test command on the `Record AppMaps` stage of the installer, AppMaps are generated, but when navigating to the next page for `Open AppMaps` - no maps are found even though AppMaps show up in the right hand view. 

<img width="1118" alt="Screen Shot 2022-08-19 at 1 23 30 PM" src="https://user-images.githubusercontent.com/511733/185674077-59d7d498-5761-407e-83df-5508ca37f864.png">

[Loom of issue](https://www.loom.com/share/d3d04da301644c14a1cd4e673bc7c48d)

**Comment by petecheslock** [comment]
Additional details - When restarting the IDE and navigating thru the onboarding wizard the "open appmaps" page will still have no results even though i have a list of AppMaps in the navigation.

**Comment by jansorg** [comment]
The initial list is now populated, https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/5fe6aae899400f1f325890e7a5f6d70dad3679e7

I still need to implement the refresh when new appmaps are created.

**Comment by jansorg** [comment]
Refresh is implemented by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/40537437bc14c5bd2a3bd050b5480999555a7b79

**Comment by petecheslock** [comment]
Confirmed fixed in `0.8.0-3`
