### ISSUE TITLE
Runtime Analysis appears in Quickstart in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#88]
The Runtime Analysis page does not currently appear in the Quickstart section:

![Image](https://user-images.githubusercontent.com/45714532/186745015-e69ba4d3-922a-45fb-a48b-ed92cc8cfc9f.png)

**Comment by jansorg** [comment]
Added by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/7689e4365d81571156274275cc7b21ea25e778f9
