### ISSUE TITLE
Selected Code Objects are populated in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#89]
There should be up to 5 AppMaps in the `HTTP Server requests` and `Queries` sections of the Explore AppMaps instruction page:

![Image](https://user-images.githubusercontent.com/45714532/186747754-e4e53d36-cae4-4c65-82e7-a3464c8b0812.png)

**Comment by petecheslock** [comment]
AppMap plugin pre-release version 0.8.0-3
IntelliJ IDEA 2022.1.2 (Community Edition)

To recreate - clone the [sample_app_6th_ed](https://github.com/land-of-apps/sample_app_6th_ed)
Checkout the codespaces-devcontainer branch.

In this example on the above version i get a placeholder request and query:
<img width="697" alt="Screen Shot 2022-08-30 at 3 37 38 PM" src="https://user-images.githubusercontent.com/511733/187528798-44841912-6da7-4422-b9b2-980abb875e7c.png">

Vs what we see in VS Code
<img width="942" alt="Screen Shot 2022-08-30 at 3 39 40 PM" src="https://user-images.githubusercontent.com/511733/187528870-96fd401a-47b0-48f3-9d1a-bf15b8a0d173.png">

**Comment by jansorg** [comment]
Thanks! This was only dummy data. classMap indexing has been added by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/c70d021ffe0a5c075fca2f0cce5f1711318f915b
