### ISSUE TITLE
Enable findings feature flag changes display of AppMap Runtime Analysis instruction page

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#90]
Currently, when the Enabled findings feature flag is checked, this page is shown:

![Image](https://user-images.githubusercontent.com/45714532/186752765-88f9891d-3431-4cf2-ac64-c236f69d76f2.png)

Instead, this page should be displayed:

![Image](https://user-images.githubusercontent.com/45714532/186753223-4b04ba70-fa92-4226-880a-ce4c4e6438e7.png)

**Comment by jansorg** [comment]
@ahtrotta Thanks! Could you try again with 0.8.0-5, please? This should be fixed now.

**Comment by jansorg** [comment]
Should be working with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
